name: Helm Unit Tests
on:
  pull_request:
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'tests/**'
      - '.github/workflows/helm-unittest.yml'

jobs:
  helm-unittest:
    name: Run Helm Unittests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Install helm-unittest plugin
        run: |
          helm plugin install https://github.com/quintush/helm-unittest --version v0.2.1

      - name: Run Helm Unittests
        run: |
          helm unittest . -f tests/*_test.yaml